// @generated by tools/gen_gpupack.py from the official archives. Do not edit by hand.
// Every file is verified against its SHA-256 after extraction.
use super::gpupack::{PackArchive, PackFile};

pub const PACK_ID: &str = "ort1.28.3-cuda12.9-cudnn9.27";

pub static ARCHIVES: &[PackArchive] = &[
    PackArchive {
        label: "ORT",
        url: "https://github.com/microsoft/onnxruntime/releases/download/v1.28.3/onnxruntime-win-x64-gpu_cuda12-1.28.3.zip",
        files: &[
            PackFile { entry: "onnxruntime-win-x64-gpu_cuda12-1.28.3/lib/onnxruntime.dll", name: "onnxruntime.dll", size: 16295224, compressed: 5688888, sha256: "40f8e2ef3bb42d9aa33041de3c83e040450e17dcef534b07aa771adb7518c060" },
            PackFile { entry: "onnxruntime-win-x64-gpu_cuda12-1.28.3/lib/onnxruntime_providers_cuda.dll", name: "onnxruntime_providers_cuda.dll", size: 496749920, compressed: 319428991, sha256: "d1354ce9f082972dcd957a7472d95e37e20625a3f1c2a24db56b9db611dbdd9b" },
            PackFile { entry: "onnxruntime-win-x64-gpu_cuda12-1.28.3/lib/onnxruntime_providers_shared.dll", name: "onnxruntime_providers_shared.dll", size: 21816, compressed: 12350, sha256: "acb3d562836ba5d139c4b323724cbe08ac0b9e1352089eecf82a525aa5a7f40f" },
        ],
    },
    PackArchive {
        label: "cudart",
        url: "https://files.pythonhosted.org/packages/59/df/e7c3a360be4f7b93cee39271b792669baeb3846c58a4df6dfcf187a7ffab/nvidia_cuda_runtime_cu12-12.9.79-py3-none-win_amd64.whl",
        files: &[
            PackFile { entry: "nvidia/cuda_runtime/bin/cudart64_12.dll", name: "cudart64_12.dll", size: 583680, compressed: 179112, sha256: "760c38928bbe5759f7b31ed6692599eb7ec83cedd5702e84c2b72028a89837e1" },
        ],
    },
    PackArchive {
        label: "cublas",
        url: "https://files.pythonhosted.org/packages/20/e2/fc9a0e985249d873150276d5afb02e39a66817fedbf1a385724393e505ed/nvidia_cublas_cu12-12.9.2.10-py3-none-win_amd64.whl",
        files: &[
            PackFile { entry: "nvidia/cublas/bin/cublas64_12.dll", name: "cublas64_12.dll", size: 102518272, compressed: 78836235, sha256: "52ce5ba0ec5327d39be6021f0f9362d2ed4d64d7206f9b5afc06398d827b8e82" },
            PackFile { entry: "nvidia/cublas/bin/cublasLt64_12.dll", name: "cublasLt64_12.dll", size: 668673536, compressed: 474126831, sha256: "71705a7cf0923f4ab034d0d2620bbfc989ff669ac3d79f868b7a7c597ca559c5" },
        ],
    },
    PackArchive {
        label: "nvrtc",
        url: "https://files.pythonhosted.org/packages/52/de/823919be3b9d0ccbf1f784035423c5f18f4267fb0123558d58b813c6ec86/nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl",
        files: &[
            PackFile { entry: "nvidia/cuda_nvrtc/bin/nvrtc-builtins64_129.dll", name: "nvrtc-builtins64_129.dll", size: 7217664, compressed: 1695815, sha256: "c405226b0b394ed8bdc593bb1419b94a989f93248ed2873e8f2e0e27c1688ca1" },
            PackFile { entry: "nvidia/cuda_nvrtc/bin/nvrtc64_120_0.dll", name: "nvrtc64_120_0.dll", size: 89832960, compressed: 37328080, sha256: "0cc63349fedffeec1660b30955e8028b6e4e4c26cf1e41c56dc4569fd5eca82c" },
        ],
    },
    PackArchive {
        label: "cudnn",
        url: "https://files.pythonhosted.org/packages/aa/38/f856579877f7c1c5066e61182e7de7bc27bf35a78c8d1b0fa592e6985bc4/nvidia_cudnn_cu12-9.27.0.42-py3-none-win_amd64.whl",
        files: &[
            PackFile { entry: "nvidia/cudnn/bin/cudnn64_9.dll", name: "cudnn64_9.dll", size: 270448, compressed: 121303, sha256: "7268ef53e32c2c574372326dfc9d94a26095f4ed9c89dba87cfb3ab1e40a6470" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_adv64_9.dll", name: "cudnn_adv64_9.dll", size: 270983792, compressed: 197358439, sha256: "712ace96559e60b5be81a1097acb7609f601ff4cd0cdef848b013d671753b4b4" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_cnn64_9.dll", name: "cudnn_cnn64_9.dll", size: 2997872, compressed: 1959066, sha256: "dff4c446c855b3ab2d486aebf4c11388cf74da14d7bd0bfafb61c3a75481313d" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_engines_precompiled64_9.dll", name: "cudnn_engines_precompiled64_9.dll", size: 528169072, compressed: 367817803, sha256: "6b603ac45fc018a96f014d0c6cdbc8f480dce2dbe33b8ca38228a4e4c531f3fe" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_engines_runtime_compiled64_9.dll", name: "cudnn_engines_runtime_compiled64_9.dll", size: 45452912, compressed: 21632138, sha256: "f92f4776261e4409aa9f84357c40bc3626700292a1d22025746388bea43ae11b" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_engines_tensor_ir64_9.dll", name: "cudnn_engines_tensor_ir64_9.dll", size: 156272, compressed: 70034, sha256: "d7380a7c4ad90590968e97b4d8b43a616e7e0070bfdeeee04c4d0be85ad52394" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_ext64_9.dll", name: "cudnn_ext64_9.dll", size: 130160, compressed: 63260, sha256: "f20888488b701e429830e19cf59022e90a0c5dd398723162ea9f320b3ca06636" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_graph64_9.dll", name: "cudnn_graph64_9.dll", size: 99919472, compressed: 40111071, sha256: "445e8c3e44a6a6035749380009ae35ae8c2bc246428229b79545a25238bb56e2" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_heuristic64_9.dll", name: "cudnn_heuristic64_9.dll", size: 94795376, compressed: 34324597, sha256: "0634af738266cd36c912e99cd3807ee452450e963bf885be204fdcfb322cfc70" },
            PackFile { entry: "nvidia/cudnn/bin/cudnn_ops64_9.dll", name: "cudnn_ops64_9.dll", size: 105686640, compressed: 79503260, sha256: "390bfe103a244c714fca5a1320950ba51a3173a7fbd6664ed535ce7367891ccd" },
        ],
    },
];

/// Load order (dependencies first). `onnxruntime.dll` itself is loaded by ONNX Runtime init.
pub static PRELOAD_ORDER: &[&str] = &[
    "cudart64_12.dll",
    "cublasLt64_12.dll",
    "cublas64_12.dll",
    "nvrtc-builtins64_129.dll",
    "nvrtc64_120_0.dll",
    "cudnn_graph64_9.dll",
    "cudnn_engines_tensor_ir64_9.dll",
    "cudnn_engines_precompiled64_9.dll",
    "cudnn_engines_runtime_compiled64_9.dll",
    "cudnn_heuristic64_9.dll",
    "cudnn_ops64_9.dll",
    "cudnn_cnn64_9.dll",
    "cudnn_ext64_9.dll",
    "cudnn_adv64_9.dll",
    "cudnn64_9.dll",
];
