"""Regenerate crates/af-core/src/ai/gpupack_data.rs (pinned GPU pack file list + SHA-256).

Download the archives listed in ARCHIVES once (they are large), then run:
    python tools/gen_gpupack.py <dir-with-archives>
Every DLL is hashed from inside the official archive; the app verifies each extracted file against it.
"""
import hashlib, os, sys, zipfile

ARCHIVES = [
    ("ORT", "https://github.com/microsoft/onnxruntime/releases/download/v1.28.3/onnxruntime-win-x64-gpu_cuda12-1.28.3.zip",
     ["onnxruntime.dll", "onnxruntime_providers_shared.dll", "onnxruntime_providers_cuda.dll"]),
    ("cudart", "https://files.pythonhosted.org/packages/59/df/e7c3a360be4f7b93cee39271b792669baeb3846c58a4df6dfcf187a7ffab/nvidia_cuda_runtime_cu12-12.9.79-py3-none-win_amd64.whl", ["cudart64_12.dll"]),
    ("cublas", "https://files.pythonhosted.org/packages/20/e2/fc9a0e985249d873150276d5afb02e39a66817fedbf1a385724393e505ed/nvidia_cublas_cu12-12.9.2.10-py3-none-win_amd64.whl", ["cublas64_12.dll", "cublasLt64_12.dll"]),
    ("nvrtc", "https://files.pythonhosted.org/packages/52/de/823919be3b9d0ccbf1f784035423c5f18f4267fb0123558d58b813c6ec86/nvidia_cuda_nvrtc_cu12-12.9.86-py3-none-win_amd64.whl", ["nvrtc64_120_0.dll", "nvrtc-builtins64_129.dll"]),
    ("cudnn", "https://files.pythonhosted.org/packages/aa/38/f856579877f7c1c5066e61182e7de7bc27bf35a78c8d1b0fa592e6985bc4/nvidia_cudnn_cu12-9.27.0.42-py3-none-win_amd64.whl",
     ["cudnn64_9.dll", "cudnn_graph64_9.dll", "cudnn_ops64_9.dll", "cudnn_cnn64_9.dll", "cudnn_heuristic64_9.dll", "cudnn_engines_precompiled64_9.dll",
      "cudnn_engines_runtime_compiled64_9.dll", "cudnn_engines_tensor_ir64_9.dll", "cudnn_ext64_9.dll", "cudnn_adv64_9.dll"]),
]
ORDER = ["cudart64_12.dll", "cublasLt64_12.dll", "cublas64_12.dll", "nvrtc-builtins64_129.dll", "nvrtc64_120_0.dll", "cudnn_graph64_9.dll",
         "cudnn_engines_tensor_ir64_9.dll", "cudnn_engines_precompiled64_9.dll", "cudnn_engines_runtime_compiled64_9.dll", "cudnn_heuristic64_9.dll",
         "cudnn_ops64_9.dll", "cudnn_cnn64_9.dll", "cudnn_ext64_9.dll", "cudnn_adv64_9.dll", "cudnn64_9.dll"]


def main():
    src = sys.argv[1]
    out = ["// @generated by tools/gen_gpupack.py from the official archives. Do not edit by hand.",
           "// Every file is verified against its SHA-256 after extraction.",
           "use super::gpupack::{PackArchive, PackFile};", "",
           'pub const PACK_ID: &str = "ort1.28.3-cuda12.9-cudnn9.27";', "", "pub static ARCHIVES: &[PackArchive] = &["]
    for label, url, names in ARCHIVES:
        z = zipfile.ZipFile(os.path.join(src, url.rsplit("/", 1)[1]))
        out += ["    PackArchive {", f'        label: "{label}",', f'        url: "{url}",', "        files: &["]
        for info in z.infolist():
            base = info.filename.split("/")[-1]
            if base in names:
                data = z.read(info)
                out.append(f'            PackFile {{ entry: "{info.filename}", name: "{base}", size: {len(data)}, compressed: {info.compress_size}, sha256: "{hashlib.sha256(data).hexdigest()}" }},')
        out += ["        ],", "    },"]
    out += ["];", "", "/// Load order (dependencies first). `onnxruntime.dll` itself is loaded by ONNX Runtime init.",
            "pub static PRELOAD_ORDER: &[&str] = &["] + [f'    "{n}",' for n in ORDER] + ["];"]
    dst = os.path.join(os.path.dirname(__file__), "..", "crates", "af-core", "src", "ai", "gpupack_data.rs")
    open(dst, "w", encoding="utf-8").write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
